Feature/homework 2
ValeriyPokatilo/FocusStartHomeworks pull request #4
Opened 2020-10-23 09:10 UTC by ValeriyPokatilo

Реализован потокобезопасный массив с универсальным шаблоном, с проверкой.

2020-10-26 09:30 UTC, korshunigor commented
Принято на проверку

2020-10-26 11:36 UTC, korshunigor requested changes
1) Рас в рамках данного пула происходит добавление gitignore файла, давай дополним его еще исключениями для macOS, чтобы отсутствовали .DS_Store файлы (которые добавляются в этом пуле. Перейди на gitignore.io, укажи там Swift, macOS, Xcode, Objective-C, и заменим имеющиеся сейчас исключения на сгенерированные сайтом
2) Какая-то беда с проектом. Открывая HomeWorks.xcworkspace на уровне проектов есть ссылка на .swift файл, которого нет (метка №1), в самом проекте с ДЗ №2 есть ссылка на файл, который почему-то не обнаруживается Xcode-ом (маркер №2), при этом сам файл лежит в проекте (метка №3), из-за чего проект не собирается, это надо починить. Для этого открой проект, удали ссылки на отсутствующий файл, затем, перетащи в Xcode файл с исходным кодом (в сам проект, туда где ты хочешь его разместить в инспекторе).

<img width="781" alt="Скрин 1" src="https://user-images.githubusercontent.com/17854702/97167419-ce164a80-1797-11eb-8a11-98082684a5ce.png">


<img width="607" alt="Скрин 2" src="https://user-images.githubusercontent.com/17854702/97167415-cc4c8700-1797-11eb-9b2c-e0cdbbd3cb8a.png">

После починки ветки приступлю к ревью самого решения.

2020-10-26 13:40 UTC, ValeriyPokatilo commented
> 1. Рас в рамках данного пула происходит добавление gitignore файла, давай дополним его еще исключениями для macOS, чтобы отсутствовали .DS_Store файлы (которые добавляются в этом пуле. Перейди на gitignore.io, укажи там Swift, macOS, Xcode, Objective-C, и заменим имеющиеся сейчас исключения на сгенерированные сайтом
> 2. Какая-то беда с проектом. Открывая HomeWorks.xcworkspace на уровне проектов есть ссылка на .swift файл, которого нет (метка №1), в самом проекте с ДЗ №2 есть ссылка на файл, который почему-то не обнаруживается Xcode-ом (маркер №2), при этом сам файл лежит в проекте (метка №3), из-за чего проект не собирается, это надо починить. Для этого открой проект, удали ссылки на отсутствующий файл, затем, перетащи в Xcode файл с исходным кодом (в сам проект, туда где ты хочешь его разместить в инспекторе).
> 
> <img alt="Скрин 1" width="781" src="https://user-images.githubusercontent.com/17854702/97167419-ce164a80-1797-11eb-8a11-98082684a5ce.png">
> 
> <img alt="Скрин 2" width="607" src="https://user-images.githubusercontent.com/17854702/97167415-cc4c8700-1797-11eb-9b2c-e0cdbbd3cb8a.png">
> 
> После починки ветки приступлю к ревью самого решения.

Внес изменения в Пул, попробуйте пожалуйста еще раз собрать проект!

2020-10-26 15:27 UTC, korshunigor requested changes

2020-10-26 15:27 UTC, korshunigor commented on HomeWork-2/HomeWork-2/ThreadSafeArray.swift
> +struct ThreadSafeArray<Element>{
1) потерялся пробел перед фигурной скобкой
2) в текущем виде массив не является потокобезопасным, т.к. если выполнить условие демонстрации результата (описано в комментарии к ViewController) произойдет race condition. Рекомендую все-таки [ознакомиться со статьей](https://m.habr.com/ru/post/320152/), которая была приложена в качестве вспомогательного материала, там данная проблема очень хорошо изложена и представлен способ ее решения (на примере потокобезопасной строки).

2020-10-26 15:27 UTC, korshunigor commented on HomeWork-2/HomeWork-2/ThreadSafeArray.swift
> +	var elements = [Element]()
Давай сделаем приватным, т.к. наш ThreadSafeArray по сути является оберткой над обычным массивом, немного странно давать прямой доступ к нему.

2020-10-26 15:27 UTC, korshunigor commented on HomeWork-2/HomeWork-2/ThreadSafeArray.swift
> +		elements.append(item)
Давай везде, где есть обращение к свойствам/методам, объявленным на уровне "self" явным образом указывать обращение к self. Например тут:
```swift
self.elements.append(item)
```

2020-10-26 15:27 UTC, korshunigor commented on HomeWork-2/HomeWork-2/ThreadSafeArray.swift
> +		return elements.isEmpty ? true : false
Если прочитать написанное "на русском" получится примерно так: верни мне истину, если является истинной то что массив пуст, иначе, верни ложь. Кажется можно упростить =)

2020-10-26 17:49 UTC, ValeriyPokatilo commented
1 Да, я видел сообщения в Телеграме об упрощении демонстрации работы, поэтому на демонстрации идет заполнение только одного массива. Надеюсь все понял правильно!
2 Очередь изменил на синхронную, в соотвествии с тем как боролись с race condition авторы статьи, дабы заполнению массива ничто не могло помешать.
Спасибо!

2020-10-26 18:08 UTC, korshunigor commented
> 1 Да, я видел сообщения в Телеграме об упрощении демонстрации работы, поэтому на демонстрации идет заполнение только одного массива. Надеюсь все понял правильно!
> 2 Очередь изменил на синхронную, в соотвествии с тем как боролись с race condition авторы статьи, дабы заполнению массива ничто не могло помешать.
> Спасибо!

И все же осталось некое недопонимание. Демонстрация действительно упрощенная, но она упрощена только в разрезе того что не надо заполнять обычный массив, при этом по прежнему должно быть две **асинхронных** задачи, одновременно выполняющих добавление элементов в один и тот же потокобезопасный массив. Должно получиться что-то такое:
```swift
queue.async {
    for number in 1...1000 {
        array.append(String(number))
    }
}

queue.async {
    for number in 1...1000 {
        array.append(String(number))
    }
}

print("Количество элементов: \(array.count)")
```
При этом тебе надо сделать так, чтобы print вывелся только после того как завершатся обе асинхронных задачи.

Изменение очереди async на sync действительно решает проблему race condition, но в данном случае это запрещено по условию, в статье описано другое решение на примере создания потокобезопасной строки.

2020-10-26 18:20 UTC, ValeriyPokatilo commented
Теперь понял, исправляю!

2020-10-26 20:03 UTC, ValeriyPokatilo commented
В классе массива, в методе append асинхронно посылаю запрос в очередь, а для заполнения добавил обе задачи в группу, после выполнения задачи делаю принт с количеством.

2020-10-26 20:22 UTC, korshunigor requested changes

2020-10-26 20:22 UTC, korshunigor commented on HomeWork-2/HomeWork-2/ThreadSafeArray.swift
> +final class ThreadSafeArray<Element> {
Где-то потерялся метод:
```swift
contains(_ element:) -> Bool
```
На всякий случай уточню, класс объявлен правильно, в соответствии с требованием "должен работать с любым типом данных". Для проверки наличия элемента в коллекции удобно использовать [расширение с оговоркой where](https://swiftbook.ru/content/languageguide/generics-in-swift/#extensions-with-a-generic-where-clause)

2020-10-26 20:22 UTC, korshunigor commented on HomeWork-2/HomeWork-2/ThreadSafeArray.swift
> +		queue.async(flags: .barrier) {
queue лежит на уровне self, давай явно укажем это (и ниже в методе remove тоже)

2020-10-26 20:22 UTC, korshunigor commented on HomeWork-2/HomeWork-2/ViewController.swift
> +		demonstration()
Данный метод лежит на уровне self, давай укажем это явно

2020-10-26 20:22 UTC, korshunigor commented on HomeWork-2/HomeWork-2/ThreadSafeArray.swift
> +}
Так, с добавлением все хорошо, race condition исключен в сценарии, когда несколько задач исполняются одновременно и пытаются удалять/добавлять данные, однако, он все еще возможен, когда мы пытаемся извлечь данные из массива и параллельно с этим удаляем/добавляем данные. Для избежания проблем с многопоточность, любое обращение к self.elements должно происходить с использованием изолированной очереди (как при добавлении, так и при извлечении значений).

Давай еще на всякий случай подстрахуемся, попобуем обработать возможные ситуации, когда при удалении/вызове сабскрипта мы пытаемся выйти за пределы массива (как в плюс, так и в минус).  Способ реализации на твое усмотрение (генерация ошибок с помощью throw или возвращение опционала) там где посчитаешь это нужным.

2020-10-27 09:31 UTC, ValeriyPokatilo commented
Внес исправления.

2020-10-27 09:57 UTC, ValeriyPokatilo commented
Вспомнил про вопрос в Телеграме про неявно развернутый опционал, переделаю!

2020-10-27 10:55 UTC, ValeriyPokatilo commented
Переделал свойства и методы с неявно развернутым опционалом.

2020-10-28 19:01 UTC, korshunigor requested changes
Не большие правки остались )

2020-10-28 19:16 UTC, ValeriyPokatilo commented
Поправил!

2020-10-29 15:17 UTC, ValeriyPokatilo commented
Можно мерджить?

2020-10-30 06:38 UTC, korshunigor approved these changes
Все ок, можно мержить

2020-10-30 15:16 UTC, merged