Feature/homework 5
ValeriyPokatilo/FocusStartHomeworks pull request #7
Opened 2020-11-16 20:14 UTC by ValeriyPokatilo

Домашнее задание №5

Выбранная архитектура - VIPER

За основу взял проект который писал ранее (https://github.com/ValeriyPokatilo/CurrencyApp) курсы валют с сайта ЦБ РФ в формате json.

CurrencyViewController -  таблица со списком всех валют и их курсами.
ConverterViewController - при нажатии на ячейку первого экрана происходит переход на второй экран с конвертером валюты в обе стороны.

CountryView  - вью котороя дважды используется на втором экране для отображения двух аргументов конвертации.

TodayRate - родительская модель для json
Valute - основная модель для json вложенная в  TodayRate
AnotherValute - альтерантивная модель для презентера второго экрана

2020-11-16 20:17 UTC, noreasonwhyiamhere commented
задание принято на проверку)

2020-11-24 07:12 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/Cell/CurrencyCell.swift
> +	var nameLabel = UILabel()
уровни доступа

2020-11-24 07:13 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/Cell/CurrencyCell.swift
> +		switch valute.toUp {
используем тут if

2020-11-24 07:14 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/Converter/ConverterInteractor.swift
> +										  imageName: valute.CharCode ?? "",
форматирование

2020-11-24 07:14 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/Converter/ConverterInteractor.swift
> +		if let newValueDouble = Double(newValue) {
guard

2020-11-24 07:15 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/Converter/ConverterInteractor.swift
> +											  imageName: valute.CharCode ?? "",
форматирование

2020-11-24 07:17 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/Converter/ConverterConfigurator.swift
> +		let interactor = ConverterInteractor(presenter: presenter, valute: valute)
Интерактор не должен знать ничего о презентере

2020-11-24 07:17 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/Converter/ConverterConfigurator.swift
> +		let presenter = ConverterPresenter(view: view)
сетаем интерактор в конструкторе

2020-11-24 07:18 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/Converter/ConverterPresenter.swift
> +	var interactor: ConverterInteractorProtocol!
избавляемся от опциональности

2020-11-24 07:21 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/Converter/ConverterConfigurator.swift
> +		let presenter = ConverterPresenter(view: view)
![image](https://user-images.githubusercontent.com/3608113/100061196-48ea8800-2e60-11eb-8822-3a4fab2ff4a6.png)
если это необходимо то должны быть нотификаторы

2020-11-24 07:22 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/CurrencyList/CurrencyPresenter.swift
> +	var router: CurrencyRouterProtocol!
избавляемся от опциональности интерактора и роутера

2020-11-24 07:22 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/CurrencyList/CurrencyPresenter.swift
> +		if valutes.indices.contains(indexPath.row) {
guard

2020-11-24 07:22 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/Model/Font.swift
> +				return UIFont.init(name: "AppleSDGothicNeo-SemiBold", size: 16.0)!
проверь форматирование по всему проекту

2020-11-24 07:23 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/Model/Font.swift
> +	public var font: UIFont {
паблик нужен?

2020-11-24 07:24 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/Network/NetworkManager.swift
> +		let jsonUrlString = "https://www.cbr-xml-daily.ru/daily_json.js"
вынести в проперти класса

2020-11-24 07:24 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/Views/CountryView.swift
> +	let nameLabel = UILabel()
уровни доступа

2020-11-24 07:25 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/CurrencyList/CurrencyViewController.swift
> +	var presenter: CurrencyPresenterProtocol!
сетаем в конструкторе и избавляемся от опциональности, меняем уровни доступа

2020-11-24 07:26 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/CurrencyList/CurrencyViewController.swift
> +			navigationController?.navigationBar.standardAppearance = navBarAppearance
где-то селфы есть, а где-то нет

2020-11-24 07:27 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/CurrencyList/CurrencyViewController.swift
> +		let cell = self.tableView.dequeueReusableCell(withIdentifier: cellID,
выносим в guard

2020-11-24 07:27 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/CurrencyList/CurrencyViewController.swift
> +		return 90
Это тоже константа, нужно положить в метрики

2020-11-24 07:28 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/CurrencyList/CurrencyRouter.swift
> +	weak var viewController: CurrencyViewController!
уровень доступа + ! ->?

2020-11-24 07:29 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/Cell/CurrencyCell.swift
> +extension CurrencyCell {
уровень доступа

2020-11-24 07:30 UTC, Jinfaa requested changes
Требуются доработки

2020-11-24 19:07 UTC, ValeriyPokatilo commented
Здравствуйте!
Я уже внес все мелкий правки по тексту кода.
Касательно форматирования, в проекте все выглядит корректно.

1 - Вопрос по замечаниям касающихся непосредственно архитектуры:
При выполнении задания я старался следовать архитектуре VIPER а именно ее трактованию описанному в книге от Rambler, так как это наиболее описанный в интернете и часто встречающийся вариант (например тут https://habr.com/ru/post/358412/)
Я сделал поиск по приведенной Вами схеме и нашел вот эту статью
https://medium.com/flawless-app-stories/implementing-viper-archticture-pattern-for-ios-d24a6def8ba2
Насколько я вижу реализация VIPER тут отличается о той что я использовал, явно указана односторонняя связь между интерактором и презентором, отсутствует конфигуратор.
Я сейчас пробую сделать такой вариант но пока не получается.
Есть ли какая-то более полная документация по этому варианту или какие то примеры? Или может можно как-то созвониться проговорить это?
2 - И вопрос по свойствам в виде неявно развернутых опционалов: их можно сделать просто опциональными или нужно сразу инициализировать какими то значениями?

2020-11-28 03:27 UTC, Jinfaa requested changes
Требуются доработки по старым замечаниям и новым

2020-11-28 03:27 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/Network/NetworkManager.swift
> +	let jsonUrlString = "https://www.cbr-xml-daily.ru/daily_json.js"
уровень доступа

2020-11-28 03:27 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/Cell/CurrencyCell.swift
> +	var nameLabel = UILabel()
не поправлено

2020-11-28 03:27 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/Converter/ConverterInteractor.swift
> +	weak var presenter: PresenterOutputProtocol!
уровень доступа и переименовать в output

2020-11-28 03:27 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/Converter/ConverterInteractor.swift
> +	private var valute: Valute
изменяться будет? если нет то let

2020-11-28 03:27 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/CurrencyList/CurrencyConfigurator.swift
> +		let interactor = CurrencyInteractor(presenter: presenter)
давай тогда презентер у нас сам сообщит интерактору что у него есть output и тем самым мы избавимся от опциональнсотей

2020-11-28 03:27 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/CurrencyList/CurrencyInteractor.swift
> +	weak var presenter: CurrencyInteractorOutputProtocol? = CurrencyPresenter(view: CurrencyViewController())
уровень доступа + именование

2020-11-28 03:27 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/CurrencyList/CurrencyPresenter.swift
> +	weak var view: CurrencyViewProtocol? = CurrencyViewController()
уровень доступа

2020-11-28 03:27 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/Converter/ConverterViewController.swift
> +	private var roubleValuteView = CountryView()
давай это сложим в отдельную view и добавим в контроллер, презентеру отдадим не контроллер, созданную view

2020-11-28 03:27 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/Converter/ConverterViewController.swift
> +	var presenter: ConverterPresenterProtocol?
избавляемся от опциональности передаем в конструктор

2020-12-01 17:15 UTC, ValeriyPokatilo commented
- Архитектура изменена на MVVM
- Переработан второй экран
- Изменен дизайн приложения

2020-12-03 14:49 UTC, Jinfaa requested changes
старые и новые правки требуются

2020-12-03 14:49 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/Cell/CurrencyCellViewModel.swift
> +													 nominal: valute.Nominal,
форматирование

2020-12-03 14:49 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/Converter/ConverterViewController.swift
> +		self.numberPadView.button1.addTarget(self, action: #selector(button1Pressed), for: UIControl.Event.touchUpInside)
ооо, минифицировать можем же, этот код сложно поддерживаемый

2020-12-03 14:49 UTC, Jinfaa commented on HomeWork-5/HomeWork-5/Service/TextFormatter.swift
> +						  nominal: Int?,
форматирование

2020-12-03 15:26 UTC, Jinfaa commented
Можно мержить

2020-12-03 15:29 UTC, merged